apiVersion: v1
kind: Service
metadata:
  name: Vgrafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000 
    nodePort: 32000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Vgrafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-con
        image: vimal13/grafana
        volumeMounts:
        - name: grafana-storage-volume
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage-volume
        persistentVolumeClaim:
          claimName: grafana-storage-pvc


